<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <None Include="index.html" />
        <TypeScriptCompile Include="language\asp.ts" />
        <Compile Include="Navigation Bar.fs" />
        <Compile Include="Button Level.fs" />
        <Compile Include="Libs\Monaco.fs" />
        <Compile Include="Monaco Editor.fs" />
        <Compile Include="Extensions.fs" />
        <Compile Include="Components.fs" />
        <Compile Include="Parsec.fs" />
        <Compile Include="Logic.fs" />
        <Compile Include="Propositional Logic.fs" />
        <Compile Include="First-order Logic.fs" />
        <Compile Include="Meta Logic.fs" />
        <Compile Include="Proof Interface.fs" />
        <Compile Include="Language.fs" />
        <Compile Include="Main.fs" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Feliz" Version="2.6.0" />
        <PackageReference Include="Feliz.Bulma" Version="3.0.0" />
        <PackageReference Include="Feliz.Bulma.Switch" Version="3.0.0" />
        <PackageReference Include="Feliz.Router" Version="4.0.0" />
        <PackageReference Include="Fable.DateFunctions" Version="3.9.0" />
        <PackageReference Update="FSharp.Core" Version="7.0.300" />
    </ItemGroup>
</Project>