<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Tests.fs" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\src\App.fsproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Fable.Mocha" Version="2.16.0" />
        <PackageReference Update="FSharp.Core" Version="7.0.200" />
        <PackageReference Include="FsLexYacc" Version="11.0.1" />
        <PackageReference Include="FsLexYacc.Runtime" Version="11.0.1" />
    </ItemGroup>
</Project>