<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <None Include="index.html" />
        <TypeScriptCompile Include="language\language.ts" />
        <Compile Include="Env.fs" />
        <Compile Include="Extensions.fs" />

        <Compile Include="Contexts.fs" />
        <Compile Include="Rules.fs" />
        <Compile Include="Language Reference.fs" />
        <Compile Include="Parsing Help.fs" />
        <Compile Include="Button Level.fs" />
        <Compile Include="Footer.fs" />
        <Compile Include="Navigation Bar.fs" />
        <Compile Include="Editor.fs" />

        <Compile Include="About.fs" />
        <Compile Include="Settings.fs" />
        <Compile Include="Home.fs" />

        <Compile Include="Main.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Forma.Common\Forma.Common.fsproj" />
        <ProjectReference Include="..\Uiw.ReactColor\Uiw.ReactColor.fsproj" />
        <ProjectReference Include="..\React.MonacoEditor\React.MonacoEditor.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Feliz" Version="2.9.0" />
        <PackageReference Include="Feliz.Bulma" Version="4.2.0" />
        <PackageReference Include="Feliz.Router" Version="4.0.0" />
    </ItemGroup>
</Project>