<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Parsing.test.fs" />
        <Compile Include="Evaluation.test.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Forma.Common\Forma.Common.fsproj" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Fable.Mocha" Version="2.17.0" />
    </ItemGroup>

</Project>
